---
title: "Walidacja krzyżowa i bootstrap"
author: Jakub Myśliwiec, Filip Twardy
output: html_document
---

```{r}
ds = read.csv('data.csv')
head(ds)
```


```{r}
names(ds)
```

```{r}
dim(ds)
# removing last columns as it's full of NA values
ds = ds[-33]
dim(ds)
```

```{r}
names(ds)
```


```{r}
set.seed(1)

n <- nrow(ds)
  
train <- sample(n, n / 2)

ds_lm <- lm(radius_mean ~ area_mean , data=ds, subset = train)

validation_set <- ds[-train,]

mse <- mean((validation_set$radius_mean - predict(ds_lm, validation_set))^2)

mse
```

```{r}
for (i in 2:8) {
  ds_lm_poly <- lm(radius_mean ~ poly(area_mean, degree = i), data = ds,  subset = train) 
  print(mean((validation_set$radius_mean - predict(ds_lm_poly, validation_set))^2)) }
```

```{r}
set.seed(2)
train <- sample(n, n / 2)
validation_set <- ds[-train,]
degree_max <- 5
mse <- rep(0, times = degree_max)
for (i in 1:degree_max) {
  ds_lm <- lm(radius_mean ~ poly(area_mean, degree = i), data = ds, subset = train)
  mse[i] <- mean((validation_set$radius_mean - predict(ds_lm, validation_set))^2)
}
mse
```

```{r}
compute_mse <- function(degree, train) {
  ds_lm <- lm(radius_mean ~ poly(area_mean, degree), data = ds, subset = train)
  validation_set <- ds[-train,]
  mean((validation_set$radius_mean - predict(ds_lm, validation_set))^2)
}

mse <- sapply(1:degree_max, compute_mse, train = train)
mse
```


```{r}
mse <- vapply(1:degree_max, compute_mse, FUN.VALUE = numeric(1), train = train)
```



```{r}
plot(mse, xlab = "Stopień wielomianu", ylab = "MSE", type = "b", pch = 20, 
     col = "blue")
```







